apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-argo-application
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://github.com/sergeykonkin/argocd-test.git
    targetRevision: HEAD
    path: application.yaml

  - repoURL: https://github.com/sergeykonkin/argocd-test.git
    targetRevision: HEAD
    path: local

  destination: 
    server: https://kubernetes.default.svc
    namespace: podinfo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
