apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sergeykonkin/argocd-test.git
    targetRevision: HEAD
    path: applications

  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
