apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prunetest
  namespace: argocd
  labels:
    app: prunetest
spec:
  source:
    repoURL: https://github.com/sergeykonkin/argocd-test.git
    targetRevision: HEAD
    path: prunetest

  destination: 
    server: https://kubernetes.default.svc
    namespace: prunetest

  project: default
