---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.crds.example.org
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
  labels:
    app.kubernetes.io/name: foo
    app.kubernetes.io/version: 6.7.1
spec:
  group: crds.example.org
  names:
    kind: Foo
    listKind: FooList
    singular: foo
    plural: foos
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Foo is the Schema for the foos API.
        type: object
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: FooSpec defines the desired state of Foo.
            type: object
            properties:
              text:
                type: string
              flag:
                type: boolean
          status:
            description: FooStatus defines the observed state of Foo.
            type: object
            properties:
              state:
                type: string
    served: true
    storage: true
    subresources:
      status: {}
