apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-deployment
  labels:
    app.kubernetes.io/name: foo
    app.kubernetes.io/version: 6.7.1
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: foo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foo
        app.kubernetes.io/version: 6.7.1
    spec:
      containers:
      - name: foo
        image: ghcr.io/stefanprodan/podinfo:6.7.1
        ports:
        - containerPort: 9898
