---
apiVersion: v1
kind: Service
metadata:
  name: foo-service
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
  labels:
    app.kubernetes.io/name: foo
    app.kubernetes.io/version: 6.7.1
spec:
  selector:
    app.kubernetes.io/name: foo
  ports:
    - protocol: TCP
      port: 9898
      targetPort: 9898
  type: ClusterIP
