apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-deployment
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/version: 6.7.1
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podinfo
        app.kubernetes.io/version: 6.7.1
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo:6.7.1
        ports:
        - containerPort: 9898
