# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: podinfo-service
# spec:
#   selector:
#     app: podinfo
#   ports:
#     - protocol: TCP
#       port: 9898
#       targetPort: 9898
#   type: ClusterIP
