---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-service
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/version: 6.7.1
spec:
  selector:
    app.kubernetes.io/name: podinfo
  ports:
    - protocol: TCP
      port: 9898
      targetPort: 9898
  type: ClusterIP
